Weighted Flooding Simulator: /home/guilhermemtr/Dropbox/workspace/ETH-Zurich/Projects/Weighted-Flooding-Simulator/include/random_utils.h File Reference
random_utils.h File Reference
#include <random>
#include <unordered_set>
#include <string.h>
#include "yal_log.h"
#include "scoped_lock.h"
Classes
class random_generator
class used for creating random generators.
Functions
void init_random_utils ()
Initializes the randomness utility functions.
std::mt19937_64 * get_random_generator ()
Generates a new random generator with a fresh seed.
Function Documentation
get_random_generator()
std::mt19937_64 * get_random_generator ()
Generates a new random generator with a fresh seed.
Returns
a pointer to a new random generator.
Referenced by get_corrupted_parties().
init_random_utils()
void init_random_utils ()
Initializes the randomness utility functions.
Referenced by init(), and run_command_parameters().