Weighted Flooding Simulator: stake_distribution_generator Class Reference
stake_distribution_generator Class Reference
Class for generating stake distributions.
#include <generate_stake_distribution.h>
Public Member Functions
stake_distribution_generator ()
std::vector< stake_t > constant_stake (party_t nr_parties, stake_t s=100)
Generates a constant stake distribution with the given parameters.
std::vector< stake_t > few_heavy_light_stake (party_t nr_parties, double heavy_light_ratio, size_t nr_heavy)
Generates a few heavy stake distribution with the given parameters, and where the sender is the lightest party.
std::vector< stake_t > few_heavy_heavy_stake (party_t nr_parties, double heavy_light_ratio, size_t nr_heavy)
Generates a few heavy stake distribution with the given parameters, and where the sender is the heaviest party.
std::vector< stake_t > exponential_lightest_stake (party_t nr_parties, double heaviest_lightest_ratio)
Generates an exponential stake distribution with the given parameters, and where the sender is the lightest party.
std::vector< stake_t > exponential_median_stake (party_t nr_parties, double heaviest_lightest_ratio)
Generates an exponential stake distribution with the given parameters, and where the sender is the party with the median wealth/weight.
std::vector< stake_t > exponential_heaviest_stake (party_t nr_parties, double heaviest_lightest_ratio)
Generates an exponential stake distribution with the given parameters, and where the sender is the heaviest party.
std::vector< stake_t > sample_uniform_stake (party_t nr_parties, stake_t lower_bound=0, stake_t upper_bound=1000000)
Generates a stake distribution with the given number of parties, where the stake of each party is picked according to a uniform distribution with parameters <parameter lower_bound> and <parameter upper_bound>, and where the sender is a random party.
std::vector< stake_t > sample_geometric_stake (party_t nr_parties, double p=0.5)
Generates a stake distribution with the given number of parties, where the stake of each party is picked according to a geometric distribution with parameter <parameter p>, and where the sender is a random party.
std::vector< stake_t > sample_exponential_stake (party_t nr_parties, double lambda=0.001)
Generates a stake distribution with the given number of parties, where the stake of each party is picked according to an exponential distribution with parameter <parameter p>, and where the sender is a random party.
void add_to_stake_distribution (std::vector< stake_t > &stakes, stake_t v)
Adds, for each party in the stake distribution, <parameter v> additional stake.
void mult_stake_distribution (std::vector< stake_t > &stakes, double factor)
Multiplies the stake of each party in the stake distribution by a factor <parameter factor>.
Protected Member Functions
std::vector< stake_t > few_heavy_stake (party_t nr_parties, double heavy_light_ratio, size_t nr_heavy)
Generates a few heavy stake distribution with the given parameters.
std::vector< stake_t > exponential_stake (party_t nr_parties, double heaviest_lightest_ratio)
Generates an exponential stake distribution with the given parameters.
Protected Attributes
std::random_device rd
< variables used to get randomness
std::default_random_engine re
default random engine
Detailed Description
Class for generating stake distributions.
Class responsible for generating stake distributions.
Constructor & Destructor Documentation
stake_distribution_generator()
stake_distribution_generator::stake_distribution_generator ()
Member Function Documentation
add_to_stake_distribution()
void stake_distribution_generator::add_to_stake_distribution (std::vector< stake_t > & stakes, stake_t v)
Adds, for each party in the stake distribution, <parameter v> additional stake.
Parameters
the stake distribution.
the additional stake to be added to each party.
Referenced by generate_stake_distribution().
constant_stake()
std::vector< stake_t > stake_distribution_generator::constant_stake (party_t nr_parties, stake_t s = 100)
Generates a constant stake distribution with the given parameters.
Parameters
the number of parties.
the stake of each party.
Returns
the stake distribution.
Referenced by generate_stake_distribution().
exponential_heaviest_stake()
std::vector< stake_t > stake_distribution_generator::exponential_heaviest_stake (party_t nr_parties, double heaviest_lightest_ratio)
Generates an exponential stake distribution with the given parameters, and where the sender is the heaviest party.
By convention, the sender is the first party in the vector output by this method.
Parameters
the number of parties.
the ratio between the stake of the heaviest and lightest party(ies).
Returns
the corresponding stake distribution.
Referenced by generate_stake_distribution().
exponential_lightest_stake()
std::vector< stake_t > stake_distribution_generator::exponential_lightest_stake (party_t nr_parties, double heaviest_lightest_ratio)
Generates an exponential stake distribution with the given parameters, and where the sender is the lightest party.
By convention, the sender is the first party in the vector output by this method.
Parameters
the number of parties.
the ratio between the stake of the heaviest and lightest party(ies).
Returns
the corresponding stake distribution.
Referenced by generate_stake_distribution().
exponential_median_stake()
std::vector< stake_t > stake_distribution_generator::exponential_median_stake (party_t nr_parties, double heaviest_lightest_ratio)
Generates an exponential stake distribution with the given parameters, and where the sender is the party with the median wealth/weight.
By convention, the sender is the first party in the vector output by this method.
Parameters
the number of parties.
the ratio between the stake of the heaviest and lightest party(ies).
Returns
the corresponding stake distribution.
Referenced by generate_stake_distribution().
exponential_stake()
std::vector< stake_t > stake_distribution_generator::exponential_stake (party_t nr_parties, double heaviest_lightest_ratio) protected
Generates an exponential stake distribution with the given parameters.
Parameters
the number of parties.
the ratio between the stake of the heaviest and lightest party(ies).
Returns
the corresponding stake distribution.
few_heavy_heavy_stake()
std::vector< stake_t > stake_distribution_generator::few_heavy_heavy_stake (party_t nr_parties, double heavy_light_ratio, size_t nr_heavy)
Generates a few heavy stake distribution with the given parameters, and where the sender is the heaviest party.
By convention, the sender is the first party in the vector output by this method.
Parameters
the number of parties.
the ratio between the stake of the heaviest and lightest party(ies).
the number of heavy parties.
Returns
the corresponding stake distribution.
Referenced by generate_stake_distribution().
few_heavy_light_stake()
std::vector< stake_t > stake_distribution_generator::few_heavy_light_stake (party_t nr_parties, double heavy_light_ratio, size_t nr_heavy)
Generates a few heavy stake distribution with the given parameters, and where the sender is the lightest party.
By convention, the sender is the first party in the vector output by this method.
Parameters
the number of parties.
the ratio between the stake of the heaviest and lightest party(ies).
the number of heavy parties.
Returns
the corresponding stake distribution.
Referenced by generate_stake_distribution().
few_heavy_stake()
std::vector< stake_t > stake_distribution_generator::few_heavy_stake (party_t nr_parties, double heavy_light_ratio, size_t nr_heavy) protected
Generates a few heavy stake distribution with the given parameters.
Parameters
the number of parties.
the ratio between the stake of the heaviest and lightest party(ies).
the number of heavy parties.
Returns
the corresponding stake distribution.
mult_stake_distribution()
void stake_distribution_generator::mult_stake_distribution (std::vector< stake_t > & stakes, double factor)
Multiplies the stake of each party in the stake distribution by a factor <parameter factor>.
Parameters
the stake distribution.
the multiplicative factor.
sample_exponential_stake()
std::vector< stake_t > stake_distribution_generator::sample_exponential_stake (party_t nr_parties, double lambda = 0.001)
Generates a stake distribution with the given number of parties, where the stake of each party is picked according to an exponential distribution with parameter <parameter p>, and where the sender is a random party.
By convention, the sender is the first party in the vector output by this method.
Parameters
the number of parties.
the parameter for the exponential distribution.
Returns
the corresponding stake distribution.
Referenced by generate_stake_distribution().
sample_geometric_stake()
std::vector< stake_t > stake_distribution_generator::sample_geometric_stake (party_t nr_parties, double p = 0.5)
Generates a stake distribution with the given number of parties, where the stake of each party is picked according to a geometric distribution with parameter <parameter p>, and where the sender is a random party.
By convention, the sender is the first party in the vector output by this method.
Parameters
the number of parties.
the parameter for the geometric distribution.
Returns
the corresponding stake distribution.
Referenced by generate_stake_distribution().
sample_uniform_stake()
std::vector< stake_t > stake_distribution_generator::sample_uniform_stake (party_t nr_parties, stake_t lower_bound = 0, stake_t upper_bound = 1000000)
Generates a stake distribution with the given number of parties, where the stake of each party is picked according to a uniform distribution with parameters <parameter lower_bound> and <parameter upper_bound>, and where the sender is a random party.
By convention, the sender is the first party in the vector output by this method.
Parameters
the number of parties.
the first parameter for the uniform distribution.
the second parameter for the uniform distribution.
Returns
the corresponding stake distribution.
Referenced by generate_stake_distribution().
Member Data Documentation
rd
std::random_device stake_distribution_generator::rd protected
< variables used to get randomness
random device
re
std::default_random_engine stake_distribution_generator::re protected
default random engine
The documentation for this class was generated from the following file:
/home/guilhermemtr/Dropbox/workspace/ETH-Zurich/Projects/Weighted-Flooding-Simulator/include/generate_stake_distribution.h